graph TD
  Arden_Vul["Arden Vul"]
  Azure_Keep["Azure Keep"]
  Cliff_Face["Cliff Face"]
  Forum_of_Arden_Vul["Forum of Arden Vul"]
  Glory_of_Thoth["Glory of Thoth"]
  Gog_s_cave["Gog's cave"]
  Gosterwick["Gosterwick"]
  Great_Cavern["Great Cavern"]
  Great_Hall["Great Hall"]
  Halls_of_Thoth["Halls of Thoth"]
  Imperial_Road["Imperial Road"]
  Long_Stair["Long Stair"]
  Narsileon["Narsileon"]
  Newmarket["Newmarket"]
  Pyramid_of_Thoth["Pyramid of Thoth"]
  Swift_River["Swift River"]
  Temple_of_Mitra["Temple of Mitra"]
  Temple_of_Set["Temple of Set"]
  Water_Gate["Water Gate"]
  Waterfall["Waterfall"]
  Well_of_Light["Well of Light"]
  Gosterwick -->|via Teleportation Rugs; Testing| Narsileon
  Gosterwick --> Narsileon
  Gosterwick -->|via Hike; Hike| Cliff_Face
  Cliff_Face -->|via Levitate| Long_Stair
  Gosterwick --> Cliff_Face
  Cliff_Face --> Long_Stair
  Gosterwick -->|via Old Imperial Road; Hiking| Swift_River
  Gosterwick --> Swift_River
  Gosterwick --> Water_Gate
  Cliff_Face -->|Hiked| Arden_Vul
  Gosterwick --> Cliff_Face
  Imperial_Road --> Arden_Vul
  Newmarket --> Arden_Vul
  Cliff_Face -->|via plunge pool| Waterfall
  Cliff_Face -->|via Long Stair; Walk| Arden_Vul
  Arden_Vul -->|via steps down into pyramid; Walk| Pyramid_of_Thoth
  Cliff_Face --> Arden_Vul
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Stairs; Magical Flight or Rope| Glory_of_Thoth
  Well_of_Light -->|via Teleportation| Great_Hall
  Well_of_Light -->|via Teleportation| Gog_s_cave
  Long_Stair -->|via Beastman Secret Entrance; Shape Earth| Great_Cavern
  Pyramid_of_Thoth --> Glory_of_Thoth
  Well_of_Light --> Great_Hall
  Well_of_Light --> Gog_s_cave
  Long_Stair --> Great_Cavern
  Newmarket --> Arden_Vul
  Long_Stair -->|via South; Down| Cliff_Face
  Cliff_Face -->|via Wheelbarrow; Traced Back| Gosterwick
  Gosterwick --> Arden_Vul
  Arden_Vul --> Swift_River
  Arden_Vul --> Forum_of_Arden_Vul
  Forum_of_Arden_Vul --> Well_of_Light
  Arden_Vul --> Cliff_Face
  Gosterwick --> Temple_of_Mitra
  Azure_Keep -->|via Cliff Face; travel| Arden_Vul
  Azure_Keep --> Arden_Vul
  Cliff_Face -->|via Imperial Road; travel, via Knights of the Azure Shield| Arden_Vul
  Azure_Keep --> Arden_Vul
  Cliff_Face -->|via ruins and basement then through halflings and desecrated Temple of Thoth; travel| Temple_of_Set
  Azure_Keep --> Arden_Vul
  Arden_Vul --> Cliff_Face
  Gosterwick -->|via None; On Foot| Temple_of_Mitra
  Azure_Keep -->|via Cliff Face; Travel by foot| Arden_Vul
  Cliff_Face -->|via Settite Basket site; Travel by foot| Arden_Vul
  Azure_Keep --> Arden_Vul
  Arden_Vul --> Cliff_Face
  Arden_Vul -->|via Imperial Road; Travel| Cliff_Face
  Cliff_Face -->|via Levitation; Climb| Long_Stair
  Arden_Vul --> Cliff_Face
  Gosterwick -->|via Cliff Face| Arden_Vul
  Arden_Vul --> Cliff_Face
  Arden_Vul -->|via Long Stair; Climb| Cliff_Face
  Forum_of_Arden_Vul -->|via Long Stair; Walk| Cliff_Face
  Arden_Vul --> Cliff_Face
  Arden_Vul --> Forum_of_Arden_Vul
  Arden_Vul -->|Instructed| Newmarket
  Arden_Vul --> Newmarket
  Swift_River --> Arden_Vul
  Arden_Vul -->|via Top Of Well; Teleportation| Well_of_Light
  Cliff_Face -->|via Teleportation via Rug| Gosterwick
  Gosterwick --> Cliff_Face
  Gosterwick --> Cliff_Face
  Arden_Vul -->|via Long Stair| Great_Cavern
  Great_Cavern -->|via Rug; Step Through| Gosterwick
  Arden_Vul --> Great_Cavern
  Newmarket --> Gosterwick
  Gosterwick --> Arden_Vul
  Gosterwick -->|Market| Arden_Vul
  Halls_of_Thoth -->|via Lever on Top of Triangular Pyramid| Great_Cavern
  Halls_of_Thoth -->|via Lever on Top of Triangular Pyramid| Great_Cavern
