graph TD
  Arden_Vul["Arden Vul"]
  Beacon["Beacon"]
  Cliff_Face["Cliff Face"]
  Forum_of_Arden_Vul["Forum of Arden Vul"]
  Forum_of_Set["Forum of Set"]
  Glory_of_Thoth["Glory of Thoth"]
  Gog_s_cave["Gog's cave"]
  Gosterwick["Gosterwick"]
  Great_Cavern["Great Cavern"]
  Great_Chasm["Great Chasm"]
  Great_Hall["Great Hall"]
  Great_Pyramid["Great Pyramid"]
  Hall_of_Judgment["Hall of Judgment"]
  Halls_of_Thoth["Halls of Thoth"]
  Howling_Caves["Howling Caves"]
  Inn_of_the_Broken_Head["Inn of the Broken Head"]
  Long_Stair["Long Stair"]
  Newmarket["Newmarket"]
  Pyramid_of_Thoth["Pyramid of Thoth"]
  Sighing_Stair["Sighing Stair"]
  Swift_River["Swift River"]
  Temple_of_Set["Temple of Set"]
  Tower_of_Scrutiny["Tower of Scrutiny"]
  Well_of_Light["Well of Light"]
  Yellow_Cloak_Inn["Yellow Cloak Inn"]
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Pyramid_of_Thoth -->|via Statue Arms Forward; Stairs| Glory_of_Thoth
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Forum_of_Set --> Great_Hall
  Pyramid_of_Thoth --> Glory_of_Thoth
  Pyramid_of_Thoth --> Glory_of_Thoth
  Pyramid_of_Thoth --> Glory_of_Thoth
  Newmarket --> Arden_Vul
  Forum_of_Arden_Vul --> Well_of_Light
  Gosterwick --> Well_of_Light
  Arden_Vul --> Cliff_Face
  Sighing_Stair -->|via Top; Running at full speed| Temple_of_Set
  Sighing_Stair --> Temple_of_Set
  Cliff_Face -->|via Hiking| Gosterwick
  Arden_Vul --> Well_of_Light
  Howling_Caves -->|via West| Hall_of_Judgment
  Gosterwick -->|via Howling Caves; traveled| Well_of_Light
  Well_of_Light -->|via Goblin Great Hall, map from Temrin; followed the map| Temple_of_Set
  Temple_of_Set -->|via Halls of Thoth, Gog's cave, Stamelis' bust; brought| Beacon
  Gosterwick --> Well_of_Light
  Pyramid_of_Thoth -->|via None; Exploration| Well_of_Light
  Cliff_Face -->|via Long Stair method: Walk| Arden_Vul
  Arden_Vul -->|Walk| Pyramid_of_Thoth
  Cliff_Face --> Arden_Vul
  Cliff_Face -->|via Long Stair; Walk| Arden_Vul
  Arden_Vul -->|via steps down into pyramid; Walk| Pyramid_of_Thoth
  Cliff_Face --> Arden_Vul
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Gosterwick --> Arden_Vul
  Arden_Vul --> Swift_River
  Sighing_Stair -->|via Top; Running at full speed| Temple_of_Set
  Sighing_Stair --> Temple_of_Set
  Sighing_Stair -->|via Top; Running| Temple_of_Set
  Sighing_Stair --> Temple_of_Set
  Swift_River --> Arden_Vul
  Tower_of_Scrutiny --> Pyramid_of_Thoth
  Gosterwick --> Cliff_Face
  Pyramid_of_Thoth -->|via None; Exploration| Well_of_Light
  Great_Chasm -->|via Lever on Top of Triangular Pyramid, Teleporter to Well of Light| Pyramid_of_Thoth
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Gosterwick -->|Susarra's murder| Yellow_Cloak_Inn
  Gosterwick --> Yellow_Cloak_Inn
  Gosterwick -->|via Long Stair; Hiked| Cliff_Face
  Gosterwick --> Cliff_Face
  Gosterwick -->|via Long Stair; Hiking| Cliff_Face
  Gosterwick --> Cliff_Face
  Cliff_Face -->|via Long Stair; climbing| Great_Cavern
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Great_Hall -->|via Beastman Secret Entrance| Great_Cavern
  Forum_of_Set -->|via Basket| Swift_River
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Great_Hall --> Great_Cavern
  Gosterwick -->|Step Through Rug| Arden_Vul
  Arden_Vul -->|via Long Stair| Great_Cavern
  Great_Cavern -->|via Long Stair; Step Through Rug| Inn_of_the_Broken_Head
  Arden_Vul --> Great_Cavern
  Arden_Vul -->|Step Through| Gosterwick
  Arden_Vul --> Gosterwick
  Gosterwick -->|via Secret Door; Levitation| Cliff_Face
  Cliff_Face -->|via Secret Door; Rug of Instant Access| Great_Cavern
  Gosterwick -->|via Rug of Instant Access; Teleportation| Great_Cavern
  Gosterwick -->|via Secret Door; Rug of Instant Access| Cliff_Face
  Great_Cavern -->|via Secret Door; Rug of Instant Access| Cliff_Face
  Cliff_Face --> Great_Cavern
  Gosterwick --> Great_Cavern
  Gosterwick --> Cliff_Face
  Great_Cavern --> Cliff_Face
  Long_Stair -->|via Two-Thirds Up| Gosterwick
  Arden_Vul -->|stairs| Halls_of_Thoth
  Arden_Vul --> Great_Pyramid
