graph TD
  Arden_Vul["Arden Vul"]
  Cliff_Face["Cliff Face"]
  Forum_of_Arden_Vul["Forum of Arden Vul"]
  Forum_of_Set["Forum of Set"]
  Glory_of_Thoth["Glory of Thoth"]
  Gog_s_cave["Gog's cave"]
  Gosterwick["Gosterwick"]
  Great_Cavern["Great Cavern"]
  Great_Hall["Great Hall"]
  Hall_of_Judgment["Hall of Judgment"]
  Howling_Caves["Howling Caves"]
  Inn_of_the_Broken_Head["Inn of the Broken Head"]
  Long_Stair["Long Stair"]
  Newmarket["Newmarket"]
  Pyramid_of_Thoth["Pyramid of Thoth"]
  Sighing_Stair["Sighing Stair"]
  Swift_River["Swift River"]
  Temple_of_Mitra["Temple of Mitra"]
  Temple_of_Set["Temple of Set"]
  Waterfall["Waterfall"]
  Well_of_Light["Well of Light"]
  Yellow_Cloak_Inn["Yellow Cloak Inn"]
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Stairs; Magical Flight or Rope| Glory_of_Thoth
  Well_of_Light -->|via Teleportation| Great_Hall
  Well_of_Light -->|via Teleportation| Gog_s_cave
  Long_Stair -->|via Beastman Secret Entrance; Shape Earth| Great_Cavern
  Pyramid_of_Thoth --> Glory_of_Thoth
  Well_of_Light --> Great_Hall
  Well_of_Light --> Gog_s_cave
  Long_Stair --> Great_Cavern
  Newmarket --> Arden_Vul
  Forum_of_Arden_Vul --> Well_of_Light
  Gosterwick -->|Vallium Ferried via Flight| Temple_of_Mitra
  Sighing_Stair -->|via Top; Running at full speed| Temple_of_Set
  Sighing_Stair --> Temple_of_Set
  Arden_Vul --> Well_of_Light
  Howling_Caves -->|via West| Hall_of_Judgment
  Gosterwick --> Well_of_Light
  Pyramid_of_Thoth -->|via None; Exploration| Well_of_Light
  Cliff_Face -->|via Long Stair method: Walk| Arden_Vul
  Arden_Vul -->|via dusty stairs| Pyramid_of_Thoth
  Cliff_Face --> Long_Stair
  Cliff_Face -->|via Long Stair; Walk| Arden_Vul
  Arden_Vul -->|via less-used entrance; Push statue's arms up| Pyramid_of_Thoth
  Cliff_Face --> Arden_Vul
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Pyramid_of_Thoth -->|via Statue Arms Forward; Stairs| Glory_of_Thoth
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth --> Glory_of_Thoth
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Gosterwick --> Arden_Vul
  Arden_Vul --> Swift_River
  Sighing_Stair -->|via Top; Running at full speed| Temple_of_Set
  Sighing_Stair --> Temple_of_Set
  Swift_River --> Arden_Vul
  Gosterwick --> Cliff_Face
  Pyramid_of_Thoth -->|via None; Exploration| Well_of_Light
  Long_Stair -->|via Hiking| Pyramid_of_Thoth
  Pyramid_of_Thoth -->|via Manipulating Statue's Arms, Reading Graffiti, Walking Down Several Hundred Stairs| Glory_of_Thoth
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Statue Arms Forward And Stairs To Glory Of Thoth; Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Statue Arms Up And Stairs To Pit To Scorpion Teleporter; Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Statue Arms Up And Stairs To Pit To Scorpion Teleporter; Teleportation| Great_Cavern
  Great_Hall -->|via Teleportation| Gog_s_cave
  Great_Hall -->|via Teleportation| Great_Cavern
  Forum_of_Set --> Pyramid_of_Thoth
  Forum_of_Set --> Pyramid_of_Thoth
  Forum_of_Set --> Pyramid_of_Thoth
  Forum_of_Set --> Pyramid_of_Thoth
  Gosterwick -->|Susarra's murder| Yellow_Cloak_Inn
  Gosterwick --> Yellow_Cloak_Inn
  Gosterwick -->|via Long Stair; Hiked| Cliff_Face
  Gosterwick --> Cliff_Face
  Gosterwick -->|via Long Stair; Hiking| Cliff_Face
  Gosterwick --> Cliff_Face
  Cliff_Face -->|via Long Stair; climbing| Great_Cavern
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Pyramid_of_Thoth -->|via Statue Arms Forward; Stairs| Glory_of_Thoth
  Pyramid_of_Thoth -->|via Teleportation| Great_Hall
  Pyramid_of_Thoth -->|via Teleportation| Gog_s_cave
  Great_Cavern -->|via Beastman Secret Entrance From Long Stair| Great_Hall
  Forum_of_Set --> Great_Hall
  Pyramid_of_Thoth --> Great_Hall
  Pyramid_of_Thoth --> Gog_s_cave
  Great_Cavern --> Great_Hall
  Waterfall -->|Vallium led them north to the statue of The Philosopher| Great_Cavern
  Arden_Vul -->|via Long Stair| Great_Cavern
  Great_Cavern -->|via Long Stair; Step Through Rug| Inn_of_the_Broken_Head
  Arden_Vul --> Great_Cavern
  Gosterwick -->|via Hike| Long_Stair
  Long_Stair -->|via Levitate; Levitation| Cliff_Face
  Great_Cavern -->|via Double Back| Great_Cavern
